# .circleci/config.yml

version: 2.1

jobs:
  # This build job just tests that the binary can build.
  build:
    docker:
      - image: golang:1.14
    environment:
      CGO_ENABLED: '1'  # go-sqlite3 requires cgo enabled.
    working_directory: /go/src/github.com/hansingt/GoatCheese
    steps:
      - checkout
      - run: make build

  # golangci-lint runs dozens of linters in parallel on your project. It is the
  # best Go linter.
  lint:
    docker:
      - image: golangci/golangci-lint:latest-alpine
    environment:
      GO111MODULE: 'on'
    working_directory: /go/src/github.com/hansingt/GoatCheese
    steps:
      - checkout
      - run: golangci-lint run

  test:
    docker:
      - image: golang:1.13
    environment:
      GO111MODULE: 'on'
    working_directory: /go/src/github.com/hansingt/GoatCheese/
    steps:
      - checkout
      - run: make cover

workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test
